name 'MDajaniCookBook'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures MDajaniCookBook'
long_description 'Installs/Configures MDajaniCookBook'
version '0.1.0'
